Controllers/NathanController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WSAD_Final_Project.Models;

namespace WSAD_Final_Project.Controllers;

public class NathanController : Controller
{
    private HobbyContext data { get; set; }

    public NathanController(HobbyContext ctx)
    {
        data = ctx;
    }

    public ViewResult Index()
    {
        var gear = data.SnowboardGear
            .OrderBy(g => g.GearType)
            .ThenBy(g => g.Brand)
            .ThenBy(g => g.Model)
            .ToList();
        return View(gear);

    }

    [HttpGet]
    public IActionResult Edit(int id)
    {
        var gear = data.SnowboardGear.Find(id);
        return View(gear);
    }

    [HttpPost]
    public IActionResult Edit(SnowboardGear gear)
    {
        if (ModelState.IsValid)
        {
            try
            {
                data.Update(gear);
                data.SaveChanges();
                TempData["Message"] = $"{gear.Brand} {gear.Model} edited successfully!";
            }
            catch
            {
                TempData["Message"] = $"Failed to edit {gear.Brand} {gear.Model}.";
            }
            return RedirectToAction("Index");
        }
        else
        {
            return View(gear);
        }
    }

    [HttpPost]
    public IActionResult Delete(int id)
    {
        var gear = data.SnowboardGear.Find(id);
        if (gear != null)
        {
            try
            {
                data.Remove(gear);
                data.SaveChanges();
                TempData["Message"] = $"{gear.Brand} {gear.Model} removed successfully!";
            }
            catch
            {
                TempData["Message"] = $"Failed to remove {gear.Brand} {gear.Model}.";
            }
        }
        else
        {
            TempData["Message"] = $"Failed to find {id}.";
        }
        return RedirectToAction("Index");
    }

    [HttpGet]
    public ViewResult Add()
    {
        return View(new SnowboardGear());
    }

    [HttpPost]
    public IActionResult Add(SnowboardGear gear)
    {
        if (ModelState.IsValid)
        {
            try
            {
                data.Add(gear);
                data.SaveChanges();
                TempData["Message"] = $"{gear.Brand} {gear.Model} added successfully!";
                return RedirectToAction("Index");
            }
            catch
            {
                TempData["Message"] = $"Failed to add {gear.Brand} {gear.Model}.";
            }
        }
        return View(gear);
    }
}

Controllers/SimonController.cs
using Microsoft.AspNetCore.Mvc;
using WSAD_Final_Project.Models;

namespace WSAD_Final_Project.Controllers
{
    public class SimonController : Controller
    {
        private HobbyContext _context { get; set; }
        public SimonController(HobbyContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var gear = _context.golfGears
            .OrderBy(g => g.Id)
            .ThenBy(g => g.Name)
            .ToList();
            return View(gear);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var gear = _context.golfGears.Find(id);
            return View(gear);
        }

        [HttpPost]
        public IActionResult Edit(GolfGear gear)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(gear);
                    _context.SaveChanges();
                    TempData["Message"] = $"{gear.Name} edited successfully!";
                }
                catch
                {
                    TempData["Message"] = $"Failed to edit {gear.Name}.";
                }
                return RedirectToAction("Index");
            }
            else
            {
                return View(gear);
            }
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            var gear = _context.golfGears.Find(id);
            if (gear != null)
            {
                try
                {
                    _context.Remove(gear);
                    _context.SaveChanges();
                }
                catch
                {
                    ModelState.AddModelError("", "Falied to remove gear");
                }
            }
            else
            {
                ModelState.AddModelError("", "Falied to find id");
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ViewResult Add() => View(new GolfGear());

        [HttpPost]
        public IActionResult Add(GolfGear gear)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Add(gear);
                    _context.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch
                {
                    ModelState.AddModelError("", "Falied to add gear");
                }
            }
            return View(gear);
        }
    }
}

Controllers/TomController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using WSAD_Final_Project.Models;

namespace WSAD_Final_Project.Controllers;

public class TomController : Controller
{
    private CarsContext data { get; set; }

    public TomController(CarsContext ctx)
    {
        data = ctx;
    }

    public ViewResult Index()
    {
        try
        {
            var cars = data.Cars
                .OrderBy(g => g.BoughtYear)
                .ThenBy(g => g.CarMake)
                .ThenBy(g => g.CarModel)
                .ToList();
            return View(cars);
        }
        catch (Exception ex)
        {
            throw;
        }
    }

    [HttpPost]
    public IActionResult Add(Cars car)
    {
        if (ModelState.IsValid)
        {
            try
            {
                data.Cars.Add(car);
                data.SaveChanges();
                TempData["SuccessMessage"] = "Car added successfully.";
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }
        }
        return View(car);
    }

    [HttpGet]
    public ViewResult Add() => View(new Cars());

    [HttpGet]
    public ViewResult Edit(int id)
    {
        try
        {
            var car = data.Cars.Find(id);
            return View(car);
        }
        catch (Exception ex)
        {
            throw;
        }
    }

    [HttpPost]
    public IActionResult Edit(Cars car)
    {
        if (ModelState.IsValid)
        {
            try
            {
                data.Cars.Update(car);
                data.SaveChanges();
                TempData["SuccessMessage"] = "Car updated successfully.";
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }
        }
        return View(car);
    }

    [HttpGet]
    public IActionResult Delete(int id)
    {
        try
        {
            var car = data.Cars.Find(id);
            if (car != null)
            {
                data.Cars.Remove(car);
                data.SaveChanges();
                TempData["SuccessMessage"] = $"{car.CarMake} {car.CarModel} was deleted";
            }
            return RedirectToAction("Index");
        }
        catch (Exception ex)
        {
            throw;
        }
    }
}

Controllers/VishvakController.cs
using Microsoft.AspNetCore.Mvc;
using WSAD_Final_Project.Models;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace WSAD_Final_Project.Controllers
{
    public class VishvakController : Controller
    {
        private GamesContext _context {  get; set; }

        public VishvakController(GamesContext context)
        {
            _context = context;
        }

        public ViewResult Index()
        {
            var games = _context.Games
            .OrderBy(c => c.ReleaseYear)
            .ThenBy(c => c.Developer)
            .ThenBy(c => c.Title)
            .ToList();

            return View(games);
        }

        [HttpGet]
        public ViewResult Add() => View(new Videogames());

        [HttpPost]
        public IActionResult Add(Videogames game)
        {
            if (ModelState.IsValid)
            {
                _context.Games.Add(game);
                _context.SaveChanges();

                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError("", "Please correct all errors");
                return View(game);
            }
        }

        [HttpGet]
        public ViewResult Edit(int id) 
        {
            var game = _context.Games.Find(id);
            return View(game);
        }

        [HttpPost]
        public IActionResult Edit(Videogames game)
        {
            if (ModelState.IsValid)
            {
                _context.Games.Update(game);
                _context.SaveChanges();

                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError("", "Please correct all errors");
                return View(game);
            }
        }

        [HttpGet]
        public ViewResult Delete(int id)
        {
            var game = _context.Games.Find(id);
            return View(game);
        }

        [HttpPost]
        public IActionResult Delete(Videogames game)
        {
            _context.Games.Remove(game);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Hobbies</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WSAD_Final_Project.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Hobbies</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Nathan" asp-action="Index">Nathan</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tom" asp-action="Index">Tom</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Vishvak" asp-action="Index">Vishvak</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Simon" asp-action="Index">Simon</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WSAD_Final_Project - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>